---
apiVersion: v1
kind: Service
metadata:
  name: car-mod-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: < ACM cert arn >
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    prometheus.io/scrape: "true"
    prometheus.io/port: "9000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: car-mod
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9000
  - name: https
    protocol: TCP
    port: 443
    targetPort: 9000
  type: LoadBalancer